service:
  greeting: Greetings From - Global Default 

additional:
  greeting: Additional Greetings From - Global Default  
  
without:
  server:
    restart: Property Added Without Server Restarted
       